name: Build and Deploy to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Maven settings.xml
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.TOKEN }}</password>
              </server>
            </servers>
            <mirrors>
              <mirror>
                <id>github</id>
                <url>https://maven.pkg.github.com/Ник/Репозиторий</url>
                <mirrorOf>*</mirrorOf>
              </mirror>
            </mirrors>
          </settings>" > ~/.m2/settings.xml

      - name: Build and deploy with Maven
        run: mvn deploy
